
title: localhostonly
description:

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Incluir CSS customizado
sass:
  style: compressed

include:
  - assets/css/custom.css
