
title: localhostonly
description: Um blog simples para publicar artigos.

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# Incluir CSS customizado
sass:
  style: compressed

include:
  - assets/css/custom.css
